SRCS = \
nnexec.cc \
NeuralNetwork.cc \
tensorflow/lite/micro/kernels/activations.cpp \
tensorflow/lite/micro/kernels/activations_common.cpp \
tensorflow/lite/micro/kernels/add.cpp \
tensorflow/lite/micro/kernels/add_common.cpp \
tensorflow/lite/micro/kernels/add_n.cpp \
tensorflow/lite/micro/kernels/arg_min_max.cpp \
tensorflow/lite/micro/kernels/assign_variable.cpp \
tensorflow/lite/micro/kernels/batch_to_space_nd.cpp \
tensorflow/lite/micro/kernels/broadcast_args.cpp \
tensorflow/lite/micro/kernels/broadcast_to.cpp \
tensorflow/lite/micro/kernels/call_once.cpp \
tensorflow/lite/micro/kernels/cast.cpp \
tensorflow/lite/micro/kernels/ceil.cpp \
tensorflow/lite/micro/kernels/circular_buffer.cpp \
tensorflow/lite/micro/kernels/circular_buffer_common.cpp \
tensorflow/lite/micro/kernels/comparisons.cpp \
tensorflow/lite/micro/kernels/concatenation.cpp \
tensorflow/lite/micro/kernels/conv.cpp \
tensorflow/lite/micro/kernels/conv_common.cpp \
tensorflow/lite/micro/kernels/cumsum.cpp \
tensorflow/lite/micro/kernels/depth_to_space.cpp \
tensorflow/lite/micro/kernels/depthwise_conv.cpp \
tensorflow/lite/micro/kernels/depthwise_conv_common.cpp \
tensorflow/lite/micro/kernels/dequantize.cpp \
tensorflow/lite/micro/kernels/dequantize_common.cpp \
tensorflow/lite/micro/kernels/detection_postprocess.cpp \
tensorflow/lite/micro/kernels/div.cpp \
tensorflow/lite/micro/kernels/elementwise.cpp \
tensorflow/lite/micro/kernels/elu.cpp \
tensorflow/lite/micro/kernels/ethosu.cpp \
tensorflow/lite/micro/kernels/exp.cpp \
tensorflow/lite/micro/kernels/expand_dims.cpp \
tensorflow/lite/micro/kernels/fill.cpp \
tensorflow/lite/micro/kernels/floor.cpp \
tensorflow/lite/micro/kernels/floor_div.cpp \
tensorflow/lite/micro/kernels/floor_mod.cpp \
tensorflow/lite/micro/kernels/fully_connected.cpp \
tensorflow/lite/micro/kernels/fully_connected_common.cpp \
tensorflow/lite/micro/kernels/gather.cpp \
tensorflow/lite/micro/kernels/gather_nd.cpp \
tensorflow/lite/micro/kernels/hard_swish.cpp \
tensorflow/lite/micro/kernels/hard_swish_common.cpp \
tensorflow/lite/micro/kernels/if.cpp \
tensorflow/lite/micro/kernels/kernel_runner.cpp \
tensorflow/lite/micro/kernels/kernel_util_micro.cpp \
tensorflow/lite/micro/kernels/l2norm.cpp \
tensorflow/lite/micro/kernels/l2_pool_2d.cpp \
tensorflow/lite/micro/kernels/leaky_relu.cpp \
tensorflow/lite/micro/kernels/leaky_relu_common.cpp \
tensorflow/lite/micro/kernels/logical.cpp \
tensorflow/lite/micro/kernels/logical_common.cpp \
tensorflow/lite/micro/kernels/logistic.cpp \
tensorflow/lite/micro/kernels/logistic_common.cpp \
tensorflow/lite/micro/kernels/log_softmax.cpp \
tensorflow/lite/micro/kernels/lstm_eval.cpp \
tensorflow/lite/micro/kernels/maximum_minimum.cpp \
tensorflow/lite/micro/kernels/micro_tensor_utils.cpp \
tensorflow/lite/micro/kernels/mirror_pad.cpp \
tensorflow/lite/micro/kernels/mul.cpp \
tensorflow/lite/micro/kernels/mul_common.cpp \
tensorflow/lite/micro/kernels/neg.cpp \
tensorflow/lite/micro/kernels/pack.cpp \
tensorflow/lite/micro/kernels/pad.cpp \
tensorflow/lite/micro/kernels/pooling.cpp \
tensorflow/lite/micro/kernels/pooling_common.cpp \
tensorflow/lite/micro/kernels/prelu.cpp \
tensorflow/lite/micro/kernels/prelu_common.cpp \
tensorflow/lite/micro/kernels/quantize.cpp \
tensorflow/lite/micro/kernels/quantize_common.cpp \
tensorflow/lite/micro/kernels/read_variable.cpp \
tensorflow/lite/micro/kernels/reduce.cpp \
tensorflow/lite/micro/kernels/reduce_common.cpp \
tensorflow/lite/micro/kernels/reshape.cpp \
tensorflow/lite/micro/kernels/resize_bilinear.cpp \
tensorflow/lite/micro/kernels/resize_nearest_neighbor.cpp \
tensorflow/lite/micro/kernels/round.cpp \
tensorflow/lite/micro/kernels/shape.cpp \
tensorflow/lite/micro/kernels/slice.cpp \
tensorflow/lite/micro/kernels/softmax.cpp \
tensorflow/lite/micro/kernels/softmax_common.cpp \
tensorflow/lite/micro/kernels/space_to_batch_nd.cpp \
tensorflow/lite/micro/kernels/space_to_depth.cpp \
tensorflow/lite/micro/kernels/split.cpp \
tensorflow/lite/micro/kernels/split_v.cpp \
tensorflow/lite/micro/kernels/squared_difference.cpp \
tensorflow/lite/micro/kernels/squeeze.cpp \
tensorflow/lite/micro/kernels/strided_slice.cpp \
tensorflow/lite/micro/kernels/sub.cpp \
tensorflow/lite/micro/kernels/sub_common.cpp \
tensorflow/lite/micro/kernels/svdf.cpp \
tensorflow/lite/micro/kernels/svdf_common.cpp \
tensorflow/lite/micro/kernels/tanh.cpp \
tensorflow/lite/micro/kernels/transpose.cpp \
tensorflow/lite/micro/kernels/transpose_conv.cpp \
tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cpp \
tensorflow/lite/micro/kernels/unpack.cpp \
tensorflow/lite/micro/kernels/var_handle.cpp \
tensorflow/lite/micro/kernels/while.cpp \
tensorflow/lite/micro/kernels/zeros_like.cpp \
tensorflow/lite/core/api/flatbuffer_conversions.cpp \
tensorflow/lite/core/api/op_resolver.cpp \
tensorflow/lite/core/api/tensor_utils.cpp \
tensorflow/lite/core/api/error_reporter.cpp \
tensorflow/lite/schema/schema_utils.cpp \
tensorflow/lite/kernels/kernel_util.cpp \
tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cpp \
tensorflow/lite/kernels/internal/quantization_util.cpp \
tensorflow/lite/c/common.cpp \
tensorflow/lite/micro/memory_helpers.cpp \
tensorflow/lite/micro/all_ops_resolver.cpp \
tensorflow/lite/micro/micro_graph.cpp \
tensorflow/lite/micro/micro_error_reporter.cpp \
tensorflow/lite/micro/micro_context.cpp \
tensorflow/lite/micro/micro_profiler.cpp \
tensorflow/lite/micro/test_helpers.cpp \
tensorflow/lite/micro/recording_micro_allocator.cpp \
tensorflow/lite/micro/micro_interpreter.cpp \
tensorflow/lite/micro/micro_time.cpp \
tensorflow/lite/micro/micro_resource_variable.cpp \
tensorflow/lite/micro/test_helper_custom_ops.cpp \
tensorflow/lite/micro/flatbuffer_utils.cpp \
tensorflow/lite/micro/mock_micro_graph.cpp \
tensorflow/lite/micro/debug_log.cpp \
tensorflow/lite/micro/micro_allocation_info.cpp \
tensorflow/lite/micro/system_setup.cpp \
tensorflow/lite/micro/micro_allocator.cpp \
tensorflow/lite/micro/micro_string.cpp \
tensorflow/lite/micro/micro_utils.cpp \
tensorflow/lite/micro/fake_micro_context.cpp \
tensorflow/lite/micro/arena_allocator/persistent_arena_buffer_allocator.cpp \
tensorflow/lite/micro/arena_allocator/recording_single_arena_buffer_allocator.cpp \
tensorflow/lite/micro/arena_allocator/non_persistent_arena_buffer_allocator.cpp \
tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.cpp \
tensorflow/lite/micro/memory_planner/greedy_memory_planner.cpp \
tensorflow/lite/micro/memory_planner/linear_memory_planner.cpp \
tensorflow/lite/micro/memory_planner/non_persistent_buffer_planner_shim.cpp

OBJS = $(addsuffix .o, $(basename $(SRCS)))

libnnexec: CC = g++
libnnexec: $(OBJS)
	$(CC) -std=c++11 -pedantic -o libnnexec.so -fPIC $(OBJS) -shared

libnnexec_win: CC = x86_64-w64-mingw32-g++
libnnexec_win: $(OBJS)
	$(CC) -std=c++11 -pedantic -o nnexec.dll -fPIC $(OBJS) -shared \
          -static-libgcc -static-libstdc++

%.o: %.c
	$(CC) -std=c++11 -pedantic -c -fPIC -O2 -I ./ $< -o $@

%.o: %.cpp
	$(CC) -std=c++11 -pedantic -c -fPIC -O2 -I ./ $< -o $@

%.o: %.cc
	$(CC) -std=c++11 -pedantic -c -fPIC -O2 -I ./ $< -o $@

clean:
	rm -f $(OBJS) libnnexec.so nnexec.dll

clean_objs:
	rm -f $(OBJS)
