name: lexci2

dependencies:
  - python==3.9.15
  - pip
  - pip:
    - ray[all]==1.13.0
    - pydantic==1.10.12
    - gym==0.21.0
    - tensorflow==2.11.0
    - pandas==2.1.1
    - dm_tree==0.1.8
    - gputil==1.4.0
    - asammdf==7.3.14
